services:
  database:
    image: postgres
    container_name: cinefun_database
    environment:
      - POSTGRES_USER=cinefun_user
      - POSTGRES_PASSWORD=cinefun_password
      - POSTGRES_DB=cinefun_db
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: eclipse-temurin:21-jdk
    volumes:
      - .:/app
      - m2_cache:/root/.m2
    working_dir: /app
    ports:
      - "8080:8080"
    command: ./mvnw verify quarkus:dev
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/cinefun_db
      QUARKUS_DATASOURCE_USERNAME: cinefun_user
      QUARKUS_DATASOURCE_PASSWORD: cinefun_password
    depends_on:
      - database

volumes:
  m2_cache:
  postgres_data:
